[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.20"

[fuzz]
runs = 1000
seed = "0x2"

[invariant]
runs = 1000
depth = 32
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

ffi = true